### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by craftmaster1231** [nsumner/llvm-demo#4] opened 2024-02-02 19:34 UTC
After steps in README, `make` gives me an error:

```
[100%] Linking CXX executable ../../bin/callcounter
/usr/bin/ld: /usr/lib64/libLLVMLanaiCodeGen.a: error adding symbols: archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
make[2]: *** [tools/callcounter/CMakeFiles/callcounter.dir/build.make:272: bin/callcounter] Error 1
make[1]: *** [CMakeFiles/Makefile2:352: tools/callcounter/CMakeFiles/callcounter.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

`ranlib /usr/lib64/libLLVMLanaiCodeGen.a` ruins arhive to be a "DOS/MBR boot sector". That's what `file` says. 
Of course, I did a backup.

OS: Fedora 39. 
llvm version: 17.0.6

**Comment by craftmaster1231** [comment] 2024-02-02 19:40
Also tried `git checkout llvm-17.0`. 
Same error.

**Comment by nsumner** [comment] 2024-02-03 22:41
I can reproduce it in the `fedora:39` docker image.

Looks like Fedora distributes an odd version of the Lanai target library.

Easiest temporary fix is to use an ubuntu docker image, You could try building llvm yourself, but I don't know why Fedora's Lanai codegen is built differently in the distributed library, so there may be more going on there.

**Comment by nsumner** [comment] 2024-02-04 21:15
It looks like the LLVM snapshots available here don't have the same problems:
https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm-snapshots/

But they are for a future version of the LLVM API that the demo does not yet support. There are a few required changes that are not nicely compatible with older versions.

So, it looks like a bug in the Fedora llvm packages, and it seems to be fixed in the packaging of llvm 18 forward.

You could also try the llvm 18 packages here:
https://copr.fedorainfracloud.org/coprs/g/fedora-llvm-team/llvm18/
This is very much unsupported. Buyer beware. It looks like llvm-devel is updated, but clang is not.

**Closed as completed by nsumner** 2024-02-04 21:15 UTC
